#!/bin/bash
# =============================================================
#  ReconStorm — Report Generator
#  Args: $1=base_dir  $2=target  $3=type
# =============================================================
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$SCRIPT_DIR/lib/logger.sh"
source "$SCRIPT_DIR/lib/utils.sh"

BASE="$1"
TARGET="${2:-unknown}"
TYPE="${3:-domain}"
REPORT="$BASE/report/summary.md"

mkdir -p "$BASE/report"

log_info "Generating report..."

cat > "$REPORT" <<EOF
# ReconStorm Findings Report

| | |
|---|---|
| **Target** | \`$TARGET\` |
| **Type** | $TYPE |
| **Date** | $(date '+%Y-%m-%d %H:%M:%S') |
| **Output** | \`$BASE\` |

---

## Recon

| Metric | Count |
|--------|-------|
| Subdomains Found | $(count_lines "$BASE/recon/subdomains.txt") |
| Live Hosts | $(count_lines "$BASE/recon/live_hosts.txt") |
| Total URLs | $(count_lines "$BASE/recon/all_urls.txt") |
| Parameterized URLs | $(count_lines "$BASE/enum/params.txt") |

EOF

# Live hosts section
if has_results "$BASE/recon/live_hosts.txt"; then
    echo "### Live Hosts (Top 20)" >> "$REPORT"
    echo '```' >> "$REPORT"
    head -n 20 "$BASE/recon/live_hosts.txt" >> "$REPORT"
    echo '```' >> "$REPORT"
fi

# Scanning section
cat >> "$REPORT" <<EOF

---

## Port Scanning

| Metric | Value |
|--------|-------|
| Target IP | $(cat "$BASE/scan/target_ip.txt" 2>/dev/null || echo "N/A") |
| Open Ports | $(count_lines "$BASE/scan/open_ports.txt") |
| Interesting Services | $(count_lines "$BASE/scan/interesting_services.txt" 2>/dev/null || echo 0) |

EOF

if has_results "$BASE/scan/open_services.txt"; then
    echo "### Open Services" >> "$REPORT"
    echo '```' >> "$REPORT"
    cat "$BASE/scan/open_services.txt" >> "$REPORT"
    echo '```' >> "$REPORT"
fi

# Vulnerability section
cat >> "$REPORT" <<EOF

---

## Vulnerabilities

| Severity | Count |
|----------|-------|
| Critical | $(grep -c "\[critical\]" "$BASE/vuln/nuclei.txt" 2>/dev/null || echo 0) |
| High | $(grep -c "\[high\]" "$BASE/vuln/nuclei.txt" 2>/dev/null || echo 0) |
| Medium | $(grep -c "\[medium\]" "$BASE/vuln/nuclei.txt" 2>/dev/null || echo 0) |
| XSS (Dalfox) | $(count_lines "$BASE/vuln/xss_dalfox.txt" 2>/dev/null || echo 0) |
| SQLi Candidates | $(count_lines "$BASE/vuln/sqli_candidates.txt" 2>/dev/null || echo 0) |
| LFI Confirmed | $(count_lines "$BASE/vuln/lfi_confirmed.txt" 2>/dev/null || echo 0) |
| Open Redirects | $(count_lines "$BASE/vuln/open_redirect.txt" 2>/dev/null || echo 0) |
| Shodan CVEs | $(count_lines "$BASE/vuln/shodan_cves.txt" 2>/dev/null || echo 0) |

EOF

if has_results "$BASE/exploit/critical_vulns.txt"; then
    echo "### Critical / High Findings" >> "$REPORT"
    echo '```' >> "$REPORT"
    cat "$BASE/exploit/critical_vulns.txt" >> "$REPORT"
    echo '```' >> "$REPORT"
fi

# Extras
cat >> "$REPORT" <<EOF

---

## Additional Findings

| Check | Result |
|-------|--------|
| Subdomain Takeover | $(count_lines "$BASE/enum/takeover.txt" 2>/dev/null || echo 0) candidates |
| CORS Misconfig | $(count_lines "$BASE/enum/cors_issues.txt" 2>/dev/null || echo 0) found |
| JS Secrets | $(count_lines "$BASE/enum/js_secrets.txt" 2>/dev/null || echo 0) potential |
| Default Creds | $(count_lines "$BASE/exploit/default_creds.txt" 2>/dev/null || echo 0) found |

---

## File Structure

\`\`\`
$BASE/
├── recon/          Subdomain enum, live hosts, URLs
├── scan/           Port scan results, nmap output
├── enum/           Directory fuzzing, params, JS analysis
├── vuln/           Nuclei, Nikto, XSS, SQLi, LFI results
├── exploit/        Confirmed findings, payloads, searchsploit
├── report/         This report
└── logs/           Full run log
\`\`\`

---
*Generated by ReconStorm v2.0 — For authorized testing only*
EOF

log_ok "Report saved: $REPORT"
